### ISSUE TITLE
Many bugs with just created app

### ISSUE THREAD

**Issue by DenisNP** [nativescript-vue/vue-cli-template#138]
### Version
Vue 2.5.22, Vue CLI 3.11.0

### Reproduction link
[https://github.com/DenisNP/empty-ns-vue-app](https://github.com/DenisNP/empty-ns-vue-app)
### Platform and OS info
Android 9 / NativeScript 6.1.2 / Windows 10

### Steps to reproduce
1. Follow these steps: https://github.com/DenisNP/empty-ns-vue-app/blob/master/README.md
It shows log with errors (see link)

2. Then fix errors: https://github.com/DenisNP/empty-ns-vue-app/commit/2c764a2e112d645e120ecd63746eaf99dba42ad8
App starts, but there is no theme at all

3. Add css manually, erase overridden ActionBar style: https://github.com/DenisNP/empty-ns-vue-app/commit/3934cf6cb1ab056ebf05bcb6624391b01b442bc8
ActionBar still white with gray text, [but it shouldn't be](https://github.com/NativeScript/theme/blob/5b60d2bea04076317c10e0577a411ff95ad79599/src/scss/variables/_orange.scss#L9), StatusBar is default with no color applied.

### What is expected?
1. App starts normally without errors right after it is created.
2. ActionBar and StatusBar is orange

### What is actually happening?
1. App dont start
2. After fix theme is not applied at all
3. After fix theme is not applied to ActionBar and StatusBar

**Comment by diezcode** [comment]
same problem here. after cloning this fresh project, I can't start anything in the preview app....

**Comment by nuochong** [comment]
@DenisNP @diezcode 

Hello, this may be caused by the latest nativescript-theme-core theme upgrade. The usage has changed since version 1.0.6, as follows:

shell
```sh
npm install @nativescript/theme --save
```
app.scss
```scss
@import "~@nativescript/theme/core";
@import "~@nativescript/theme/orange";
```
So that you can deal with your doubts

Also, the case [nativescript-vue-examples](https://github.com/nuochong/nativescript-vue-examples) may be helpful to you. You are currently unemployed and researching. There is no income. Your concern is to encourage me , Welcome star and recommend! :-)
