### ISSUE TITLE
tns process is left running when the script exits

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#5]
Im not sure if this happens every time, but sometimes if I end the `npm run watch:ios/android` command, the tns process is not killed, and it keeps syncing the app in the background.

We might need to keep the pid, and on process exit kill it

**Comment by lewebsimple** [comment]
This should be tested against the latest 0.2.0 branch...

**Comment by lewebsimple** [comment]
I think this happens because `webpack-synchronizable-shell-plugin` doesn't handle executing another `node`process.

A clean way to address this issue would be to make our own webpack plugin that listens on the compiler events and exec/spawn the various building processes directly (with proper termination if something goes wrong and making sure we only have one process).

**Comment by lewebsimple** [comment]
The new 0.3.0 branch should address this, would like some testing (especially with android+ios at once and in a windows environment)
