### ISSUE TITLE
Color Scheme : StatusBar and ActionBar color

### ISSUE THREAD

**Issue by ergofriend** [nativescript-vue/vue-cli-template#98]
I selected Color Scheme sky, but statusbar and actionbar color are #53ba82 .
Hwo do I change there color?

styles.scss imported ```~nativescript-theme-core/scss/sky``` and ```~nativescript-theme-core/scss/index```

![image](https://user-images.githubusercontent.com/29725082/46062641-68fd5e80-c1a5-11e8-8b15-c54b974d94a8.png)

**Comment by rigor789** [comment]
The StatusBar color comes from
https://github.com/nativescript-vue/vue-cli-template/blob/c03e630e5494bd767a9d3045b0315332196568b0/template/app/App_Resources/Android/src/main/res/values/colors.xml#L4

And the ActionBar itself is colored in 
https://github.com/nativescript-vue/vue-cli-template/blob/c03e630e5494bd767a9d3045b0315332196568b0/template/app/components/App.vue#L20-L24

The themes are only imported, but the classes are not applied by default. I want to tweak that to be optional, because I personally don't use them, so I don't want to have to delete extra classes whenever I create a new project... Might add that soon!
